### ISSUE TITLE
请问：是否支持mock？

### ISSUE THREAD

**Issue by whsheng** [restran/api-gateway#3]
如标题！

**Comment by restran** [comment]
你说的mock应用场景是什么？这只是一个API网关，负责处理API的管理和转发，只要按照API网关的规范，就可以将请求数据转发到后台真正处理的API服务上面。具体是什么应用并不关心，只是作为一个桥梁做转发。

**Comment by workcheng** [comment]
http://www.soasme.com/2016/05/18/api-gateway

**Comment by whsheng** [comment]
@restran ：上次提到的Mock，是指是否类似‘阿里-API网关’，支持配置Mock，这样会比较方便前期的API调试工作。

**Comment by restran** [comment]
@whsheng 不支持在网关上直接配置 Mock，但是可以配置将请求转发到后端的某个 Mock API 上。
